### ISSUE TITLE
always show after select dropdown

### ISSUE THREAD

**Issue by mannurman** [Semantic-UI-Vue/Semantic-UI-Vue#326] opened 2019-06-02 04:26 UTC
after select gender in dropdown
<img width="432" alt="Screen Shot 2019-06-02 at 11 22 40" src="https://user-images.githubusercontent.com/36145209/58756760-12f96b80-8529-11e9-9474-765802263d95.png">
still showing
<img width="419" alt="Screen Shot 2019-06-02 at 11 24 54" src="https://user-images.githubusercontent.com/36145209/58756762-18ef4c80-8529-11e9-967e-9241023d3b54.png">
what is wrong?

**Comment by mariolamacchia** [comment] 2019-10-13 10:40
Closing this as it doesn't state what the problem is. Please add more details and a link to reproduce and I'll reopen this.

**Closed by mariolamacchia** 2019-10-13 10:40 UTC
