### ISSUE TITLE
vue-events conflict: TypeError: this.$options.events[key].bind is not a function

### ISSUE THREAD

**Issue by nocturn3e** [Semantic-UI-Vue/Semantic-UI-Vue#318] opened 2019-04-25 12:58 UTC
**vue-events@3.1.0**
**semantic-ui-vue@0.8.1**

When the Vue instance uses vue-events, any semantic-ui-vue component produces the following error:

> TypeError: this.$options.events[key].bind is not a function

> [Vue warn]: Error in beforeCreate hook: "TypeError: this.$options.events[key].bind is not a function"

Bug reproduced: https://codesandbox.io/embed/oxjok13625

**Comment by mariolamacchia** [comment] 2019-10-13 11:15
Duplicate of #161

**Closed by mariolamacchia** 2019-10-13 11:15 UTC
Labels: bug
