### ISSUE TITLE
Second dropwdown don't show.

### ISSUE THREAD

**Issue by Adrek** [Semantic-UI-Vue/Semantic-UI-Vue#327] opened 2019-06-04 19:29 UTC
The dropdown menu does not show the second level of dropdown. That is, if you click on the tool icon, the sub-menu is displayed. Up to here all very well, but if you click on the word "New" the second dropdown does not appear

https://semantic-ui-vue.github.io/#/collections/menu
(First Menu)

**Comment by mariolamacchia** [comment] 2019-10-13 11:26
Duplicate of #293

**Closed by mariolamacchia** 2019-10-13 11:26 UTC
Labels: Hacktoberfest, bug
